### ISSUE TITLE
[User] 로그인시 주소값 등은 필수입력이 아님.

### ISSUE THREAD

**Issue by hana2set** [AirDnS/airDnS-back#158]
![image](https://github.com/AirDnS/airDnS-back/assets/97689567/20fd94d9-5698-4883-809b-47ad27eb1c32)

![image](https://github.com/AirDnS/airDnS-back/assets/97689567/a4d7ccfe-ae89-4a10-b1cd-51b7cba6d1ce)

**Comment by Kim-Jong-Gyu** [comment]
유저 생성시 Default Value가 생기도록 만들었습니다!!!
